export enum PaymentProviderStatuses {
  FAILED = 'FAILED',
  SUCCESS = 'SUCCESS',
  CANCELED = 'CANCELED',
  PROCESSING = 'PROCESSING',
  WAITING_PAYMENT = 'WAITING_PAYMENT',
  REQUIRE_AUTHENTICATION = 'REQUIRE_AUTHENTICATION'
}

export enum VmcCompaniesKeyNames {
  CENTER = 'STRIPE_SECRET_KEY_CENTER',
  PLATEFORME = 'STRIPE_SECRET_KEY_PLATEFORME'
}

export enum EStripePublicKeyEnv {
  PLATFORM = 'STRIPE_ALIXONE_ACCESS_KEY',
  CENTER = 'STRIPE_FERDIONE_ACCESS_KEY'
}
