export const mecaBoxEquipments: string[] = [
  'Pont élévateur',
  "Bac de récupération d'huile",
  'Kit de vidange',
  'Purgeur de freins',
  'Repousse piston de freins',
  'Clé à choc',
  'Douilles à choc',
  'Clés dynamométriques',
  'Clés mixtes',
  'Clés de tension de courroie',
  'Clés à pipe de bouchée',
  'Clés males longues (6 pans, torx à têtes sphériques)',
  'Clés à tuyauter',
  'Clé à pipe 6x6 pans 27mm',
  'Tournevis',
  'Pinces',
  'Marteaux et burins',
  'Cliquets et douilles',
  'Kit de distribution',
  'Extracteur de rotules et module extracteur',
  'Verrin de fosse',
  'Coupe tube',
  'Controleur étanchéité refroidissement',
  'Testeur de batterie, multimètre',
  'Chasse goupille, outils à dégarnir',
  'Outil à chanfreiner',
  "Fraise pour puit d'injecteur",
  'Coffret pour poulie altenateur'
]
