export const mecaBoxPrestations: string[] = [
  'Vidange moteur',
  'Révision',
  'Disques et plaquettes de frein',
  'Nettoyage de FAP (Filtre à Particules)',
  'Remplacement de FAP (Filtre à Particules)',
  'Remplacement du filtre à carburant',
  'Remplacement du filtre à air',
  "Remplacement du filtre d'habitacle",
  'Liquide de refroidissement',
  'Liquide de frein',
  'Courroie de distribution',
  "Courroie d'accessoires",
  "Bougies d'allumage",
  'Bougies de prechauffage',
  'Permutation des roues',
  'Parallelisme',
  'Géométrie',
  'Remplacement de la batterie',
  'Remplacement des balais essuie-glace',
  "Remplacement d'échappement",
  "Modification d'échappement",
  'Remplacement des ampoules de phares',
  "Vidange de l'huile de boite de vitesse",
  'Remplacement de fusible',
  'Remplacement du joint de culasse',
  "Remplacement d'amortisseurs"
]
